In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2425-data/2425_data.csv
/kaggle/input/football-predicion/E0.csv

In [2]:
data = pd.read_csv("/kaggle/input/2425-data/2425_data.csv")

In [3]:
data

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [4]:
data.shape

(380, 120)

In [5]:
text = "1XBD 1XBCA BFH	BFD	BFA	WHH WHD 1XBH  1XBA	BFCH	BFCD	BFCA	WHCH	WHCD	WHCA	1XBCH	1XBCD	1XBCA1XBD WHA FTHG FTAG HTHG HTAG HTR Div	Date Time Referee	HS	AS	HST	AST	HF	AF	HC	AC	HY	AY	HR	AR BFDH	BFDD	BFDA	BMGMH	BMGMD	BMGMA	BVH	BVD	BVA	BWH	BWD	BWA	CLH	CLD	CLA	LBH	LBD	LBA	PSH	PSD	PSA	MaxH	MaxD	MaxA	AvgH	AvgD	AvgA	BFEH	BFED	BFEA	B365>2.5	B365<2.5	P>2.5	P<2.5	Max>2.5	Max<2.5	Avg>2.5	Avg<2.5	BFE>2.5	BFE<2.5	AHh	B365AHH	B365AHA	PAHH	PAHA	MaxAHH	MaxAHA	AvgAHH	AvgAHA	BFEAHH	BFEAHA	B365CH	B365CD	B365CA	BFDCH	BFDCD	BFDCA	BMGMCH	BMGMCD	BMGMCA	BVCH	BVCD	BVCA	BWCH	BWCD	BWCA	CLCH	CLCD	CLCA	LBCH	LBCD	LBCA	PSCH	PSCD	PSCA	MaxCH	MaxCD	MaxCA	AvgCH	AvgCD	AvgCA	BFECH	BFECD	BFECA	B365C>2.5	B365C<2.5	PC>2.5	PC<2.5	MaxC>2.5	MaxC<2.5	AvgC>2.5	AvgC<2.5	BFEC>2.5	BFEC<2.5	AHCh	B365CAHH	B365CAHA	PCAHH	PCAHA	MaxCAHH	MaxCAHA	AvgCAHH	AvgCAHA	BFECAHH	BFECAHA"
cols = [f"{i}" for i in text.split()]
columns = data.columns

In [6]:
n_data = data
for i in cols:
    if i in columns:
        n_data = n_data.drop(i, axis="columns")
n_data.head()

     HomeTeam     AwayTeam FTR  B365H  B365D  B365A
0  Man United       Fulham   H   1.60   4.20   5.25
1     Ipswich    Liverpool   A   8.50   5.50   1.33
2     Arsenal       Wolves   H   1.18   7.50  13.00
3     Everton     Brighton   A   2.63   3.30   2.63
4   Newcastle  Southampton   H   1.36   5.25   8.00

In [7]:
n_data["res"] = n_data["FTR"].map({"H":0, "D":1, "A":2})
n_data

          HomeTeam     AwayTeam FTR  B365H  B365D  B365A  res
0       Man United       Fulham   H   1.60   4.20   5.25    0
1          Ipswich    Liverpool   A   8.50   5.50   1.33    2
2          Arsenal       Wolves   H   1.18   7.50  13.00    0
3          Everton     Brighton   A   2.63   3.30   2.63    2
4        Newcastle  Southampton   H   1.36   5.25   8.00    0
..             ...          ...  ..    ...    ...    ...  ...
375      Newcastle      Everton   A   1.33   5.50   8.50    2
376  Nott'm Forest      Chelsea   A   3.00   3.75   2.20    2
377    Southampton      Arsenal   A   8.50   6.00   1.30    2
378      Tottenham     Brighton   A   4.20   4.33   1.70    2
379         Wolves    Brentford   D   2.70   3.70   2.45    1

[380 rows x 7 columns]

In [8]:
t = n_data["HomeTeam"].unique()
teams = {i: val+1 for val, i in enumerate(t)}
teams

{'Man United': 1,
 'Ipswich': 2,
 'Arsenal': 3,
 'Everton': 4,
 'Newcastle': 5,
 "Nott'm Forest": 6,
 'West Ham': 7,
 'Brentford': 8,
 'Chelsea': 9,
 'Leicester': 10,
 'Brighton': 11,
 'Crystal Palace': 12,
 'Fulham': 13,
 'Man City': 14,
 'Southampton': 15,
 'Tottenham': 16,
 'Aston Villa': 17,
 'Bournemouth': 18,
 'Wolves': 19,
 'Liverpool': 20}

In [9]:
n_data["HT"] = n_data["HomeTeam"].map(teams)
n_data["AT"] = n_data["AwayTeam"].map(teams)
n_data

          HomeTeam     AwayTeam FTR  B365H  B365D  B365A  res  HT  AT
0       Man United       Fulham   H   1.60   4.20   5.25    0   1  13
1          Ipswich    Liverpool   A   8.50   5.50   1.33    2   2  20
2          Arsenal       Wolves   H   1.18   7.50  13.00    0   3  19
3          Everton     Brighton   A   2.63   3.30   2.63    2   4  11
4        Newcastle  Southampton   H   1.36   5.25   8.00    0   5  15
..             ...          ...  ..    ...    ...    ...  ...  ..  ..
375      Newcastle      Everton   A   1.33   5.50   8.50    2   5   4
376  Nott'm Forest      Chelsea   A   3.00   3.75   2.20    2   6   9
377    Southampton      Arsenal   A   8.50   6.00   1.30    2  15   3
378      Tottenham     Brighton   A   4.20   4.33   1.70    2  16  11
379         Wolves    Brentford   D   2.70   3.70   2.45    1  19   8

[380 rows x 9 columns]

In [10]:
f_drop = ["FTR", "HomeTeam", "AwayTeam"]
for i in f_drop:
    n_data = n_data.drop(i, axis="columns")
n_data

     B365H  B365D  B365A  res  HT  AT
0     1.60   4.20   5.25    0   1  13
1     8.50   5.50   1.33    2   2  20
2     1.18   7.50  13.00    0   3  19
3     2.63   3.30   2.63    2   4  11
4     1.36   5.25   8.00    0   5  15
..     ...    ...    ...  ...  ..  ..
375   1.33   5.50   8.50    2   5   4
376   3.00   3.75   2.20    2   6   9
377   8.50   6.00   1.30    2  15   3
378   4.20   4.33   1.70    2  16  11
379   2.70   3.70   2.45    1  19   8

[380 rows x 6 columns]

In [11]:
n_data["BP"] = np.where(n_data["B365A"] > n_data["B365H"], 0, 2)
n_data.head()

   B365H  B365D  B365A  res  HT  AT  BP
0   1.60   4.20   5.25    0   1  13   0
1   8.50   5.50   1.33    2   2  20   2
2   1.18   7.50  13.00    0   3  19   0
3   2.63   3.30   2.63    2   4  11   2
4   1.36   5.25   8.00    0   5  15   0

In [12]:
Y = n_data["res"]
n_data = n_data.drop("res", axis="columns")
n_data

     B365H  B365D  B365A  HT  AT  BP
0     1.60   4.20   5.25   1  13   0
1     8.50   5.50   1.33   2  20   2
2     1.18   7.50  13.00   3  19   0
3     2.63   3.30   2.63   4  11   2
4     1.36   5.25   8.00   5  15   0
..     ...    ...    ...  ..  ..  ..
375   1.33   5.50   8.50   5   4   0
376   3.00   3.75   2.20   6   9   2
377   8.50   6.00   1.30  15   3   2
378   4.20   4.33   1.70  16  11   2
379   2.70   3.70   2.45  19   8   2

[380 rows x 6 columns]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(n_data, Y, test_size = 0.2, random_state=42, stratify =Y)

In [14]:
from xgboost import XGBClassifier

clf = XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss',
    learning_rate=0.001,
    max_depth=4,
    n_estimators=100,
    random_state=42
)

clf.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.001, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_class=3, num_parallel_tree=None, ...)

In [15]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = clf.predict(X_test)
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=['Home Win', 'Draw', 'Away Win']))

Test Accuracy: 0.5526315789473685
              precision    recall  f1-score   support

    Home Win       0.56      0.71      0.63        31
        Draw       0.29      0.11      0.15        19
    Away Win       0.60      0.69      0.64        26

    accuracy                           0.55        76
   macro avg       0.48      0.50      0.48        76
weighted avg       0.51      0.55      0.51        76